name = "CodecBase"
uuid = "6c391c72-fb7b-5838-ba82-7cfb1bcfecbf"
license = "MIT"
authors = ["Kenta Sato <bicycle1885@gmail.com>"]
version = "0.3.2"

[deps]
TranscodingStreams = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"

[compat]
TranscodingStreams = "0.9, 0.10"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[targets]
test = ["Test", "Random"]
